services:
  tunnel:
    image: ghcr.io/hackycy/hackycy-cli:${YCY_VERSION:-latest}
    restart: unless-stopped
    environment:
      YCY_TUNNEL_DATA_DIR: /data
      YCY_TUNNEL_ADMIN_USER: admin
      YCY_TUNNEL_ADMIN_PASSWORD: '${YCY_TUNNEL_ADMIN_PASSWORD:?required}'
    volumes:
      - tunnel-data:/data
    ports:
      - '7000:7000/tcp'
      - '7500:7500/tcp'
      - '8080:8080/tcp'
      - '20000-20100:20000-20100/tcp'
      - '20000-20100:20000-20100/udp'

volumes:
  tunnel-data:
